# 主题设置
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "contrast", "default", "dirt", "mint", "sunrise"

# 插件支持
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# 基本设置
title: "Galaxy Idealism"
description: "Personal Knowledge Base"
url: "https://galaxy-0.github.io"
baseurl: "/Galaxy-Idealism-publish"

# 默认布局
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: false
      read_time: true
      show_date: true
      share: false

# 布局设置
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      show_date: true

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
