# 主题设置
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "contrast", "default", "dirt", "mint", "sunrise"

# 插件支持
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# 基本设置
title: "Galaxy Idealism"
description: "Personal Knowledge Base"
url: "https://galaxy-0.github.io"
baseurl: "/Galaxy-Idealism-publish"

# 布局设置
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: false
      read_time: true
      show_date: true
      share: false
      sidebar:
        - title: "相关文章"
          text: "这里是相关文章列表"
        - title: "推荐阅读"
          text: "其他推荐内容"
      toc: true
      toc_sticky: true

# 导航设置
search: true
search_full_content: true

# 分页设置
paginate: 10
paginate_path: /page:num/

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
